config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords], :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    authenticated :user do
      root 'monsters#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :monsters do
    member do
      get :team
    end
    collection do
      get :teams
    end
  end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/monster.rb
class Monster < ActiveRecord::Base
	belongs_to :user
	belongs_to :monster_type
	belongs_to :team

	validates :name, :power, :monster_type, :user, presence: true
	validates_with MonsterSizeValidator
end

app/models/monster_size_validator.rb
class MonsterSizeValidator < ActiveModel::Validator
	MONSTERS_SIZE = 20

  def validate(record)
  	user = record.user
    if user.present?
	    if user.monsters.size > MONSTERS_SIZE
	    	record.errors[:monster] << "You have already #{MONSTERS_SIZE} monsters."
	    end
	  end
  end
end

app/models/monster_type.rb
class MonsterType < ActiveRecord::Base
	has_many :monsters
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :monsters
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  MONSTERS_SIZE = 20

  has_many :monsters, dependent: :destroy
  
  validates_each :monsters do |user, attr, value|
   user.errors.add attr, "too much monsters for user" if user.monsters.size > MONSTERS_SIZE
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email = auth.info.email
      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(
          email: email,
          password: Devise.friendly_token[0,20]
        )
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy, :team]
  before_action :get_monters, only: [:index, :teams]

  def index
  end

  def show
  end

  def new
    @monster = Monster.new
  end

  def edit
  end

  def create
    @monster = current_user.monsters.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def team
  end

  def teams
    @unassigned_monsters = @monsters.where(team_id: nil)
    @team1_monsters = @monsters.where(team_id: 1)
    @team2_monsters = @monsters.where(team_id: 2)
    @team3_monsters = @monsters.where(team_id: 3)
  end

  private
    def set_monster
      @monster = Monster.find(params[:id])
    end

    def get_monters
      @monsters = current_user.monsters
    end

    def monster_params
      params.require(:monster).permit(:name, :power, :monster_type_id, :team_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:facebook].each do |provider|
    provides_callback_for provider
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubymon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
  	<%= link_to "Logoff", destroy_user_session_path, method: :delete %>
  <% end %>
	<%= yield %>

</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  Name: <%= f.text_field :name %><br />
  Power: <%= f.text_field :power %><br />
  Type: <%= f.select(:monster_type_id, MonsterType.all.collect {|mt| [mt.name, mt.id]}, :prompt => 'Select') %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<h1>Listing Monsters</h1>

<table border="1" id="monsters">
  <thead>
    <tr>
      <th data-sort="string-ins">Name</th>
      <th data-sort="string-ins">Power</th>
      <th data-sort="string-ins">Type</th>
      <th data-sort="string-ins">Team</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.monster_type.try(:name) %></td>
        <td><%= monster.team.try(:name) %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Assign Team', team_monster_path(monster) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %> | <%= link_to 'Monster Teams', teams_monsters_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p>Name: <%= @monster.name %></p>
<p>Power: <%= @monster.power %></p>
<p>Type: <%= @monster.monster_type.name %></p>
<p>Team: <%= @monster.team.try(:name) %></p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/team.html.erb
<%= form_for(@monster) do |f| %>
	<p>Name: <%= @monster.name %></p>
	<p>Power: <%= @monster.power %></p>
	<p>Type: <%= @monster.monster_type.name %></p>
	Select Team: <%= f.select(:team_id, Team.all.collect {|mt| [mt.name, mt.id]}, :prompt => 'Select') %>
	<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/teams.html.erb
<h1>Listing Monsters by Teams</h1>

<h3>With Out Team</h3>
<table id="monsters">
  <thead>
    <tr>
      <th data-sort="string-ins">Name</th>
      <th data-sort="string-ins">Power</th>
      <th data-sort="string-ins">Type</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @unassigned_monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.monster_type.try(:name) %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Assign Team', team_monster_path(monster) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<h3>Team1</h3>
<% if @team1_monsters.present? %>
  <table id="monsters1">
    <thead>
      <tr>
        <th data-sort="string-ins">Name</th>
        <th data-sort="string-ins">Power</th>
        <th data-sort="string-ins">Type</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @team1_monsters.each do |monster| %>
        <tr>
          <td><%= monster.name %></td>
          <td><%= monster.power %></td>
          <td><%= monster.monster_type.try(:name) %></td>
          <td><%= link_to 'Show', monster %></td>
          <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
          <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Change Team', team_monster_path(monster) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>There are no monster under this team.</h4>
<% end %>

<br />

<h3>Team2</h3>
<% if @team2_monsters.present? %>
  <table id="monsters2">
    <thead>
      <tr>
        <th data-sort="string-ins">Name</th>
        <th data-sort="string-ins">Power</th>
        <th data-sort="string-ins">Type</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @team2_monsters.each do |monster| %>
        <tr>
          <td><%= monster.name %></td>
          <td><%= monster.power %></td>
          <td><%= monster.monster_type.try(:name) %></td>
          <td><%= link_to 'Show', monster %></td>
          <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
          <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Change Team', team_monster_path(monster) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>There are no monster under this team.</h4>
<% end %>

<br />

<h3>Team3</h3>
<% if @team3_monsters.present? %>
  <table id="monsters3">
    <thead>
      <tr>
        <th data-sort="string-ins">Name</th>
        <th data-sort="string-ins">Power</th>
        <th data-sort="string-ins">Type</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @team3_monsters.each do |monster| %>
        <tr>
          <td><%= monster.name %></td>
          <td><%= monster.power %></td>
          <td><%= monster.monster_type.try(:name) %></td>
          <td><%= link_to 'Show', monster %></td>
          <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
          <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Change Team', team_monster_path(monster) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>There are no monster under this team.</h4>
<% end %>

<br>

<%= link_to 'Back', monsters_path %>